#---------- Cheat Sheets -------------------------------------------------------
bash         st -e nvim path/to/bash.sh
git          ghostty -e "nvim '/home/n451/Notes/21-30 Tinker/11 Unix/11.1 vim/nvim.md'"
vimwiki      firefox path/to/vimwiki.html
